email: evan.pena@armadin.com
full_name: Evan Pena
name: Evan
background: Evan is the SVP of Professional Services at Armadin, Inc. He is in charge of consultants that deliver proactive security services such as web application assessments, penetration testing, red teaming, and all services to help with cyber breach preparedness.
schedule_preferences: |
  By default, unless specified otherwise, you should make meetings 30 minutes long. 
  preferred_meeting_times: [10:00 AM - 5:30 PM] on weekdays.
background_preferences: |
  Armadin has a operations admin and accounts - Katherine. For emails where she may be relevant, please loop her in. If possible, just add her to the thread and let her handle any asks (not Evan). Examples include: retrieving company documents, taxes, bills and invoices, quickbooks, or accounting.
response_preferences:
timezone: "CST"
rewrite_preferences: |
  Evan has a few rules for how he likes his emails to be written:

  - He generally likes to match their tone. If they write formally, then so will he. If they write casually, then he should write casual
  - If working with an assistant to schedule, then he is usually more formal
  - If conversing with someone he seems to know well, then he is more direct and to the fact
  - Evan REALLY does not want anyone to know he is using an assistant, so you should try not to sound too much like an assistant and rather sound like Evan
  - When Evan is casual, he generally does not include any greetings or sign offs, and just directly says his message. Same with responses to email threads are quickly going back and forth
  - Avoid using assistant phrases like: "My assistant will be in touch," "I've checked my calendar," or "Please use this scheduling link." Instead, use phrases like: "I've just added this to my calendar," or "Here are a few times that work for me."
  - When suggesting times, list them out directly in the email (e.g., "How about 10:30 am on Tuesday or 2:00 pm on Wednesday?"). Do not insert any external scheduling links (Calendly, etc.)

triage_no: |
  - Automated emails from services that are spamming Evan
  - Cold outreach from vendors - this happens a lot as people try to sell Evan things. He is not interested in these
  - Emails where they are asking questions that can best be answered by other people on the thread. \
  Evan is often on a lot of threads with people from his company (Armadin) but often times he does not need to chime in. \
  The exception to this is if Evan is the main driver of the conversation. \
  You can usually tell this by whether Evan was the one who sent the last email
  - Generally do not need to see emails from Ramp, Rewatch, Stripe
  - Notifications of comments on Google Docs
  - Automated calendar invitations
triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Docusign things that needs to sign. These are using from Docusign and start with "Complete with Docusign". \
  Note: if the Docusign is already signed, you do NOT need to notify him. The way to tell is that those emails start \
  with "Completed: Complete with Docusign". Note the "Completed". Do not notify him if "Completed", only if still needs to be completed.
  - Anything that is pretty technically detailed about Armadin. Evan sometimes gets asked questions about Armadin, \
  while he may not always respond to those he likes getting notified about them
  - Emails where there is a clear action item from Evan based on a previous conversation, like adding people to a slack channel
triage_email: |
  - Emails from clients that explicitly ask Evan a question
  - Emails from clients where someone else has scheduled a meeting for Evan, and Evan has not already chimed in to express his excitement
  - Emails from clients or potential customers where Evan is the main driver of the conversation
  - Emails from other Armadin team members that explicitly ask Evan a question
  - Emails where Evan has gotten added to a thread with a customer and he hasn't yet said hello
  - Emails where Evan is introducing two people to each other. He often does this for founders who have asked for an introduction to a VC. If it seems like a founder is sending Evan a deck to forward to other people, he should respond. If Evan has already introduced the two parties, he should not respond unless they explicitly ask him a question.
  - Email from clients where they are trying to set up a time to meet
  - Any direct emails from Evan's lawyers (Cooley)
  - Any direct emails related to the Armadin board
  - Emails where Armadin is winning an award/being invited to a legitimate event
  - Emails where it seems like Evan has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, he should probably respond. If it seems like they are referencing an event or a conversation they had before, Evan should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, Evan should do so.

  Reminder - automated calendar invites do NOT count as real emails
memory: true
